package antiSpamFilter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.Scanner;

/**
 * @author gspas1-iscteiul
 */
public class WeightsAutomaticConfigurationReader {

	private LinkedList<WeightsSet> weightsSets = new LinkedList<>();

	/**
	 * This operation reads the file generated by jMetal with the name 'name' in a specific way
	 * @param name The name of the file to be read 
	 */
	public void readFileWithWeights(String name) {
		try {
			Scanner scanner = new Scanner (new File(name));
			try{
				while (scanner.hasNextLine()) {
					String line = scanner.nextLine();
					String[] tokens = line.split(" ");
					
					LinkedList<Double> weights = new LinkedList<>();
					
					for (int i = 0; i < tokens.length; i++) {
						double d = Double.parseDouble(tokens[i]);
						weights.add(d);
					}
					WeightsSet ws = new WeightsSet(weights);
					weightsSets.add(ws);
				}
			} finally {
				scanner.close();
			}
		} catch (FileNotFoundException e) {
			System.out.println("O ficheiro não foi encontrado");		
		}
	}
	
	
	/**
	 * Method to return the sets of weights of the file
	 * @return LinkedList - Sets of weights of the file
	 */
	public LinkedList<WeightsSet> getWeightsSets() {
		return weightsSets;
	}
}